export default function TermsPage() {
  const effective = 'July 31, 2026';
  return (
    <main style={{ background: 'var(--background)', color: 'var(--foreground)' }}>
      <section style={{ maxWidth: '760px', margin: '0 auto', padding: '6rem 2rem' }}>
        <div style={{ fontSize: '0.7rem', fontWeight: 700, color: 'var(--accent)', letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: '1rem' }}>Legal</div>
        <h1 style={{ fontSize: '2.25rem', fontWeight: 800, marginBottom: '0.5rem' }}>Terms of Service</h1>
        <p style={{ fontSize: '0.875rem', color: 'var(--muted)', marginBottom: '3rem' }}>Effective date: {effective}</p>

        {[
          {
            title: '1. Acceptance of Terms',
            body: `By accessing or using the Luminary Financial Compliance Intelligence Platform ("Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform. These Terms constitute a legally binding agreement between you and Apex Vital Holdings LLC, doing business as Luminary Financial ("Company," "we," "us," or "our").`,
          },
          {
            title: '2. Description of Service',
            body: `The Platform provides AI-powered compliance document auditing services for Registered Investment Advisers, financial institutions, and related professionals. The Platform analyzes uploaded documents against a proprietary set of compliance rules and generates findings reports. The Platform is a software tool and does not constitute legal advice, investment advice, or compliance consulting.`,
          },
          {
            title: '3. Not Legal Advice',
            body: `THE PLATFORM IS A TECHNOLOGY TOOL AND DOES NOT PROVIDE LEGAL ADVICE. All findings, reports, and outputs generated by the Platform are for informational purposes only and should not be relied upon as legal, regulatory, or compliance advice. You should consult qualified legal counsel before making compliance decisions or filing documents with any regulatory authority. The Company assumes no liability for regulatory actions, fines, or penalties arising from your reliance on Platform outputs.`,
          },
          {
            title: '4. Intellectual Property',
            body: `All Platform software, AI models, compliance rulesets, methodologies, processes, the "ICM Method," and related intellectual property are the exclusive property of Apex Vital Holdings LLC. Nothing in these Terms grants you any ownership interest in the Platform or its underlying technology. You may not reverse engineer, decompile, copy, reproduce, or otherwise attempt to derive the source code, ruleset, or methodology powering the Platform.`,
          },
          {
            title: '5. Your Documents and Data',
            body: `You retain ownership of all documents you upload to the Platform. By uploading documents, you grant the Company a limited, non-exclusive license to process those documents solely for the purpose of providing the audit service. Documents are processed and not permanently stored after analysis is complete. The Company will not use your documents to train AI models or share them with third parties, except as required by law.`,
          },
          {
            title: '6. Acceptable Use',
            body: `You agree to use the Platform only for lawful compliance review purposes. You may not use the Platform to upload documents you do not have the right to submit, to attempt to circumvent security measures, to engage in any fraudulent activity, or in any manner that violates applicable law. The Company reserves the right to terminate access for any violation of these Terms.`,
          },
          {
            title: '7. Subscription and Payment',
            body: `Access to the Platform requires a paid subscription. Subscriptions are billed monthly unless an annual contract is in place. All fees are non-refundable except as provided in the 14-day money-back guarantee offered to new subscribers. You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period.`,
          },
          {
            title: '8. Limitation of Liability',
            body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM. THE COMPANY'S TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNTS PAID BY YOU IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.`,
          },
          {
            title: '9. Disclaimer of Warranties',
            body: `THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. THE COMPANY DOES NOT WARRANT THAT THE PLATFORM WILL BE ERROR-FREE, UNINTERRUPTED, OR THAT AUDIT FINDINGS WILL BE COMPLETE OR ACCURATE FOR ALL APPLICABLE REGULATORY REQUIREMENTS.`,
          },
          {
            title: '10. Governing Law',
            body: `These Terms shall be governed by the laws of the State of Georgia, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the state or federal courts located in Fulton County, Georgia.`,
          },
          {
            title: '11. Changes to Terms',
            body: `The Company reserves the right to modify these Terms at any time. Continued use of the Platform after changes become effective constitutes acceptance of the updated Terms. Material changes will be communicated by email to registered users.`,
          },
          {
            title: '12. Contact',
            body: `Questions about these Terms may be directed to: hello@luminaryfinancial.co\nLuminary Financial LLC\nA subsidiary of Apex Vital Holdings LLC\nAtlanta, GA`,
          },
        ].map(section => (
          <div key={section.title} style={{ marginBottom: '2.5rem' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--foreground)', marginBottom: '0.75rem' }}>{section.title}</h2>
            <p style={{ fontSize: '0.9rem', color: 'var(--muted)', lineHeight: 1.8, whiteSpace: 'pre-line' }}>{section.body}</p>
          </div>
        ))}
      </section>
    </main>
  );
}
